In [190]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [191]:
# vectors are just one dimensional arrays essentially just a stright list
# matrices are two dimensional

In [192]:
# Createing numpy array

In [193]:
my_list = [1,2,3]

In [194]:
x = np.array(my_list)

In [195]:
x

array([1, 2, 3])

In [196]:
type(x)

numpy.ndarray

In [197]:
my_matrix  = [[1,2,3], [4,5,6], [6,8,9]]

In [198]:
y = np.array(my_matrix)

In [199]:
type(y)

numpy.ndarray

In [200]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [6, 8, 9]])

In [201]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [202]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [203]:
np.arange(1,11,2) #not including 11

array([1, 3, 5, 7, 9])

In [204]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [205]:
type(1)

int

In [206]:
type(1.0)

float

In [207]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [208]:
np.zeros((3,5)) # (rows, cols)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [209]:
np.ones((3,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [210]:
np.linspace(0, 10, 3)

array([  0.,   5.,  10.])

In [211]:
x = np.linspace(0, 10, 11)

In [212]:
x

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [213]:
len(x)

11

In [214]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [215]:
np.random.rand(3)

array([ 0.79149405,  0.64047172,  0.46680523])

In [216]:
np.random.rand(5,4)

array([[ 0.40413662,  0.80452256,  0.37592515,  0.3615028 ],
       [ 0.91514223,  0.06910891,  0.74808452,  0.4785268 ],
       [ 0.26977298,  0.74372093,  0.58582904,  0.04622975],
       [ 0.28128689,  0.8531429 ,  0.6562998 ,  0.22754972],
       [ 0.65389545,  0.31397898,  0.5470163 ,  0.32621893]])

In [217]:
np.random.randn(4)

array([ 0.82171327, -0.65514946, -0.51569863, -0.43826017])

In [218]:
np.random.randn(5,4)

array([[-0.12103205, -1.16180494,  0.05376009,  0.61229451],
       [ 0.58124451, -0.12735874, -0.66232494, -1.34857665],
       [ 1.13711972,  0.01395196, -0.07574652, -0.99536925],
       [-0.82711162,  0.79107675,  1.57354128,  1.41629486],
       [ 0.29160317, -1.74979192,  0.54055424,  0.1400116 ]])

In [219]:
np.random.randint(1, 100, 10) # 1 inclusive, 100 exclusive

array([27, 64, 29, 45, 47, 26, 66, 51, 32, 27])

In [221]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)
arr
ranarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

array([ 0, 30, 22, 21, 35,  8, 31, 20, 39, 39])

In [222]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [223]:
ranarr

array([ 0, 30, 22, 21, 35,  8, 31, 20, 39, 39])

In [224]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [225]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [226]:
arr.shape # 1 dimentional array

(25,)

In [227]:
arr.reshape(25,1).shape

(25, 1)

In [228]:
arr.dtype

dtype('int64')

In [229]:
ranarr

array([ 0, 30, 22, 21, 35,  8, 31, 20, 39, 39])

In [230]:
ranarr.max()

39

In [231]:
ranarr.argmax() #index location of the max value

8

In [232]:
ranarr.argmin()

0

In [233]:
arr = np.arange(0, 10)

In [234]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [235]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [236]:
arr * arr # element by element

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [237]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [238]:
arr / arr

/home/willwywang/anaconda3/envs/carnd-term1/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [239]:
1 / arr

/home/willwywang/anaconda3/envs/carnd-term1/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111])

In [240]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [241]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [242]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [243]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [244]:
np.max(arr) #universal array function

9

In [245]:
arr.max()

9

In [246]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [247]:
np.log(arr)

/home/willwywang/anaconda3/envs/carnd-term1/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458])

In [248]:
arr = np.arange(0, 11)

In [249]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [250]:
arr[8] # get index 8

8

In [251]:
arr[1:5] # get from index 1 to index 5(exclusive)

array([1, 2, 3, 4])

In [252]:
arr[:5] # get all to index 5(exclusive)

array([0, 1, 2, 3, 4])

In [253]:
arr[3:] # get all from index 3(inclusive)

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [254]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [255]:
arr[0:5] = 100 # broadcasting, we can only do it in numpy array
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [256]:
arr = np.arange(0, 11)

In [257]:
slice_of_arr = arr[0:6]

In [258]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [259]:
slice_of_arr[:] = 99

In [260]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [261]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [262]:
# We know that the slice_of_arr is not a copy, but a view of original array

In [263]:
# The reason of this, is to save memory

In [264]:
arr_copy = arr.copy() # if you really want to copy

In [265]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [266]:
arr_copy[:] = 200

In [267]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [268]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [269]:
# mat[row, col]
# mat[row][col]

In [270]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [271]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [272]:
mat[0]

array([ 5, 10, 15])

In [273]:
mat[2]

array([35, 40, 45])

In [274]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [275]:
mat[1][1]

25

In [276]:
mat[1,1] #

25

In [277]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [278]:
mat[0,2]

15

In [279]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [280]:
mat[:2, 1:] # a slice of matrix

array([[10, 15],
       [25, 30]])

In [281]:
mat[1:,:2] # two dimentioanl slicing

array([[20, 25],
       [35, 40]])

In [282]:
mat[1:, 0:2]

array([[20, 25],
       [35, 40]])

In [283]:
# Conditional selection

In [284]:
arr = np.arange(1,11)

In [285]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [286]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [287]:
bool_arr = arr > 4

In [288]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [289]:
arr[arr>4] # conditional selection

array([ 5,  6,  7,  8,  9, 10])

In [290]:
arr [arr <= 9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [291]:
1+1

2

In [292]:
arr = np.arange(1,11)

In [293]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [294]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [295]:
ran_arr = np.random.rand(10)

In [296]:
ran_arr

array([ 0.60070612,  0.01682885,  0.18793383,  0.45599905,  0.98302633,
        0.61309734,  0.62469967,  0.18224042,  0.73124016,  0.55976864])

In [297]:
arr * ran_arr

array([ 0.60070612,  0.03365769,  0.5638015 ,  1.82399621,  4.91513167,
        3.67858403,  4.37289769,  1.45792339,  6.58116145,  5.59768645])

In [298]:
for x in range(0,3):
    print("make my husband love me forever")

make my husband love me forever
make my husband love me forever
make my husband love me forever


In [299]:
?sum()

In [300]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [301]:
sum(arr, -100)

-45

In [302]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python

In [303]:
%env

{'CLICOLOR': '1',
 'COLORTERM': 'truecolor',
 'CONDA_DEFAULT_ENV': 'carnd-term1',
 'CONDA_EXE': '/home/willwywang/anaconda3/bin/conda',
 'CONDA_PREFIX': '/home/willwywang/anaconda3/envs/carnd-term1',
 'CONDA_PROMPT_MODIFIER': '(carnd-term1) ',
 'CONDA_PYTHON_EXE': '/home/willwywang/anaconda3/bin/python',
 'CONDA_SHLVL': '1',
 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-eGUWOdYhJO,guid=86f61f7965d4d5e6b8eeb9935b308f0e',
 'DESKTOP_SESSION': 'gnome-classic',
 'DISPLAY': ':0',
 'GDMSESSION': 'gnome-classic',
 'GDM_LANG': 'en_US.UTF-8',
 'GIT_PAGER': 'cat',
 'GJS_DEBUG_OUTPUT': 'stderr',
 'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG',
 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated',
 'GNOME_SHELL_SESSION_MODE': 'classic',
 'HISTCONTROL': 'ignoredups',
 'HISTSIZE': '1000',
 'HOME': '/home/willwywang',
 'HOSTNAME': 'gpu-server',
 'IMSETTINGS_INTEGRATE_DESKTOP': 'yes',
 'IMSETTINGS_MODULE': 'none',
 'JPY_PARENT_PID': '2374',
 'LANG': 'en_US.UTF-8',
 'LESSOPEN': '||/usr/bin/lesspipe.sh %s',


In [304]:
%who

InteractiveShell	 arr	 arr_copy	 bool_arr	 mat	 my_list	 my_matrix	 np	 ran_arr	 
ranarr	 slice_of_arr	 x	 y	 


In [305]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [306]:
%prun print("hello")

hello
 

In [307]:
!ls -l

total 80
drwxrwxr-x. 3 willwywang willwywang   164 Aug  9  2017 01-Python-Crash-Course
drwxrwxr-x. 3 willwywang willwywang   205 Jul 15 22:55 02-NumPy
drwxrwxr-x. 4 willwywang willwywang  4096 Aug  9  2017 03- General Pandas
drwxrwxr-x. 4 willwywang willwywang    64 Aug  9  2017 04-Visualization-Matplotlib-Pandas
drwxrwxr-x. 4 willwywang willwywang   168 Aug  9  2017 05-Pandas-with-Time-Series
drwxrwxr-x. 3 willwywang willwywang    87 Aug  9  2017 06-Data-Sources
drwxrwxr-x. 3 willwywang willwywang   193 Aug  9  2017 07-Stock-Market-Analysis-Capstone-Project
drwxrwxr-x. 3 willwywang willwywang   280 Aug  9  2017 08-Time-Series-Analysis
drwxrwxr-x. 3 willwywang willwywang  4096 Aug  9  2017 09-Python-Finance-Fundamentals
drwxrwxr-x. 3 willwywang willwywang   277 Aug  9  2017 10-Quantopian-Platform
drwxrwxr-x. 3 willwywang willwywang   247 Aug  9  2017 11-Advanced-Quantopian-Topics
-rw-rw-r--. 1 willwywang willwywang   953 Aug  9  2017 environment.yml
-rw-rw-r--. 1 willwywang willwywang 

In [308]:
!pip list | grep pandas

pandas             0.23.1   


$$ P(A \mid B) = \frac{P(B \mid A) \, P(A)}{P(B)} $$

In [309]:
import pandas as pd

In [313]:
labels = ['a', 'b', 'c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a':10, 'b':20, 'c':100}

In [314]:
pd.Series(my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [315]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [316]:
pd.Series(d)

a     10
b     20
c    100
dtype: int64

In [317]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

In [318]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [322]:
ser1 = pd.Series([1,2,3,4],index=['USA','CHINA','FRANCE','GERMANY'])

In [323]:
ser1

USA        1
CHINA      2
FRANCE     3
GERMANY    4
dtype: int64

In [324]:
ser2 = pd.Series([1,2,3,4],index=['USA','CHINA','ITALY','JAPAN'])

In [325]:
ser2

USA      1
CHINA    2
ITALY    3
JAPAN    4
dtype: int64

In [326]:
ser1['USA']

1

In [327]:
ser2['JAPAN']

4

In [330]:
ser1 + ser2

CHINA      4.0
FRANCE     NaN
GERMANY    NaN
ITALY      NaN
JAPAN      NaN
USA        2.0
dtype: float64

In [331]:
from numpy.random import randn

In [332]:
np.random.seed(101)

In [336]:
df = pd.DataFrame(randn(5, 4), ['A', 'B', 'C', 'D', 'E'], ['W', 'X', 'Y', 'Z'])

In [337]:
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [338]:
df['W']

A   -0.993263
B    1.025984
C    2.154846
D    0.147027
E   -0.925874
Name: W, dtype: float64

In [339]:
type(df['W'])

pandas.core.series.Series

In [340]:
type(df)

pandas.core.frame.DataFrame

In [341]:
df.W

A   -0.993263
B    1.025984
C    2.154846
D    0.147027
E   -0.925874
Name: W, dtype: float64

In [342]:
df['X']

A    0.196800
B   -0.156598
C   -0.610259
D   -0.479448
E    1.862864
Name: X, dtype: float64

In [343]:
df[['W', 'Z']]

W         Z
A -0.993263  0.000366
B  1.025984  0.649826
C  2.154846 -0.346419
D  0.147027  1.024810
E -0.925874  0.610478

In [344]:
df['new'] = df['W'] + df['Y']

In [345]:
df

W         X         Y         Z       new
A -0.993263  0.196800 -1.136645  0.000366 -2.129908
B  1.025984 -0.156598 -0.031579  0.649826  0.994405
C  2.154846 -0.610259 -0.755325 -0.346419  1.399521
D  0.147027 -0.479448  0.558769  1.024810  0.705796
E -0.925874  1.862864 -1.133817  0.610478 -2.059691

In [346]:
df.drop('new') 

KeyError: "labels ['new'] not contained in axis"

In [347]:
df.drop('new', axis=1) #default is axis=0

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [348]:
df

W         X         Y         Z       new
A -0.993263  0.196800 -1.136645  0.000366 -2.129908
B  1.025984 -0.156598 -0.031579  0.649826  0.994405
C  2.154846 -0.610259 -0.755325 -0.346419  1.399521
D  0.147027 -0.479448  0.558769  1.024810  0.705796
E -0.925874  1.862864 -1.133817  0.610478 -2.059691

In [349]:
df.drop('new', axis=1,inplace=True) #inplace will actually act on the df

In [350]:
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [351]:
df.drop('E', axis=0)

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810

In [352]:
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [353]:
df.shape

(5, 4)

In [354]:
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [355]:
df[['Z', 'X']]

Z         X
A  0.000366  0.196800
B  0.649826 -0.156598
C -0.346419 -0.610259
D  1.024810 -0.479448
E  0.610478  1.862864

In [356]:
# select ROWS

In [357]:
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [358]:
df.loc['A'] 

W   -0.993263
X    0.196800
Y   -1.136645
Z    0.000366
Name: A, dtype: float64

In [359]:
type(df.loc['A'])

pandas.core.series.Series

In [361]:
df.iloc[0] #index based location

W   -0.993263
X    0.196800
Y   -1.136645
Z    0.000366
Name: A, dtype: float64

In [362]:
df.loc['B','Y']

-0.031579143908112575

In [363]:
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [364]:
df.loc[['A','B'], ['W', 'Y']]

W         Y
A -0.993263 -1.136645
B  1.025984 -0.031579

In [365]:
#conditioanl selection

In [366]:
df > 0

W      X      Y      Z
A  False   True  False   True
B   True  False  False   True
C   True  False  False  False
D   True  False   True   True
E  False   True  False   True

In [367]:
booldf = df > 0

In [368]:
booldf

W      X      Y      Z
A  False   True  False   True
B   True  False  False   True
C   True  False  False  False
D   True  False   True   True
E  False   True  False   True

In [369]:
df[booldf]

W         X         Y         Z
A       NaN  0.196800       NaN  0.000366
B  1.025984       NaN       NaN  0.649826
C  2.154846       NaN       NaN       NaN
D  0.147027       NaN  0.558769  1.024810
E       NaN  1.862864       NaN  0.610478

In [370]:
df[df>0]

W         X         Y         Z
A       NaN  0.196800       NaN  0.000366
B  1.025984       NaN       NaN  0.649826
C  2.154846       NaN       NaN       NaN
D  0.147027       NaN  0.558769  1.024810
E       NaN  1.862864       NaN  0.610478

In [371]:
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [372]:
df['W']>0

A    False
B     True
C     True
D     True
E    False
Name: W, dtype: bool

In [373]:
df['W']

A   -0.993263
B    1.025984
C    2.154846
D    0.147027
E   -0.925874
Name: W, dtype: float64

In [374]:
df[df['W']>0] #The most use case

W         X         Y         Z
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810

In [380]:
resultdf = df[df['W']>0]

In [381]:
resultdf['X']

B   -0.156598
C   -0.610259
D   -0.479448
Name: X, dtype: float64

In [384]:
df[df['W']>0][['X','Y']] ########################most use case

X         Y
B -0.156598 -0.031579
C -0.610259 -0.755325
D -0.479448  0.558769

In [385]:
boolser = df['W'] > 0

In [386]:
boolser

A    False
B     True
C     True
D     True
E    False
Name: W, dtype: bool

In [387]:
result = df[boolser]

In [388]:
result

W         X         Y         Z
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810

In [389]:
mycols = ['Y', 'X']
result[mycols]

Y         X
B -0.031579 -0.156598
C -0.755325 -0.610259
D  0.558769 -0.479448

In [390]:
# multiple conditions

In [391]:
df[df['W']>0]

W         X         Y         Z
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810

In [392]:
df[(df['W']>0) and (df['Y']>1)]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [393]:
True and False

False

In [394]:
True and True

True

In [395]:
# and cannot work with Series and Series

In [397]:
df[(df['W']>0) & (df['Y']>0)] # should use & and |

W         X         Y        Z
D  0.147027 -0.479448  0.558769  1.02481

In [398]:
df[(df['W']>0) | (df['Y']>0)] # should use & and |

W         X         Y         Z
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810

In [399]:
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [400]:
df.reset_index() # not inplace

index         W         X         Y         Z
0     A -0.993263  0.196800 -1.136645  0.000366
1     B  1.025984 -0.156598 -0.031579  0.649826
2     C  2.154846 -0.610259 -0.755325 -0.346419
3     D  0.147027 -0.479448  0.558769  1.024810
4     E -0.925874  1.862864 -1.133817  0.610478

In [401]:
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [404]:
newind = 'CA NY WY OR CO'.split() #create a list

In [405]:
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [406]:
df['States'] = newind

In [407]:
df

W         X         Y         Z States
A -0.993263  0.196800 -1.136645  0.000366     CA
B  1.025984 -0.156598 -0.031579  0.649826     NY
C  2.154846 -0.610259 -0.755325 -0.346419     WY
D  0.147027 -0.479448  0.558769  1.024810     OR
E -0.925874  1.862864 -1.133817  0.610478     CO

In [410]:
df.set_index('States') # Set a column as a index

W         X         Y         Z
States                                        
CA     -0.993263  0.196800 -1.136645  0.000366
NY      1.025984 -0.156598 -0.031579  0.649826
WY      2.154846 -0.610259 -0.755325 -0.346419
OR      0.147027 -0.479448  0.558769  1.024810
CO     -0.925874  1.862864 -1.133817  0.610478

In [411]:
df

W         X         Y         Z States
A -0.993263  0.196800 -1.136645  0.000366     CA
B  1.025984 -0.156598 -0.031579  0.649826     NY
C  2.154846 -0.610259 -0.755325 -0.346419     WY
D  0.147027 -0.479448  0.558769  1.024810     OR
E -0.925874  1.862864 -1.133817  0.610478     CO

In [412]:
df.set_index('States', inplace=True)

In [413]:
df

W         X         Y         Z
States                                        
CA     -0.993263  0.196800 -1.136645  0.000366
NY      1.025984 -0.156598 -0.031579  0.649826
WY      2.154846 -0.610259 -0.755325 -0.346419
OR      0.147027 -0.479448  0.558769  1.024810
CO     -0.925874  1.862864 -1.133817  0.610478

In [414]:
#Index levels
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1,2,3,1,2,3]

In [416]:
hier_index = list(zip(outside, inside))

In [417]:
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [419]:
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [420]:
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [421]:
df = pd.DataFrame(randn(6,2), hier_index, ['A', 'B'])

In [422]:
df

A         B
G1 1  0.386030  2.084019
   2 -0.376519  0.230336
   3  0.681209  1.035125
G2 1 -0.031160  1.939932
   2 -1.005187 -0.741790
   3  0.187125 -0.732845

In [425]:
df.loc['G1']

A         B
1  0.386030  2.084019
2 -0.376519  0.230336
3  0.681209  1.035125

In [427]:
df.loc['G1'].loc[1]

A    0.386030
B    2.084019
Name: 1, dtype: float64

In [428]:
df.index.names

FrozenList([None, None])

In [429]:
df.index.names = ['Groups', 'Num']

In [430]:
df

A         B
Groups Num                    
G1     1    0.386030  2.084019
       2   -0.376519  0.230336
       3    0.681209  1.035125
G2     1   -0.031160  1.939932
       2   -1.005187 -0.741790
       3    0.187125 -0.732845

In [431]:
df.loc['G2']

A         B
Num                    
1   -0.031160  1.939932
2   -1.005187 -0.741790
3    0.187125 -0.732845

In [432]:
df.loc['G2'].loc[2]

A   -1.005187
B   -0.741790
Name: 2, dtype: float64

In [433]:
df.loc['G2'].loc[2]['B']

-0.74178970466892491

In [434]:
df

A         B
Groups Num                    
G1     1    0.386030  2.084019
       2   -0.376519  0.230336
       3    0.681209  1.035125
G2     1   -0.031160  1.939932
       2   -1.005187 -0.741790
       3    0.187125 -0.732845

In [435]:
df.loc['G1']

A         B
Num                    
1    0.386030  2.084019
2   -0.376519  0.230336
3    0.681209  1.035125

In [436]:
df.xs('G1')

A         B
Num                    
1    0.386030  2.084019
2   -0.376519  0.230336
3    0.681209  1.035125

In [437]:
df.xs(1, level='Num')

A         B
Groups                   
G1      0.38603  2.084019
G2     -0.03116  1.939932